/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/areas': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Areas */
    get: operations['list_areas_api_v1_areas_get'];
    put?: never;
    /** Create Area */
    post: operations['create_area_api_v1_areas_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/areas/{area_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Area */
    patch: operations['patch_area_api_v1_areas__area_id__patch'];
    trace?: never;
  };
  '/api/v1/audit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Audit */
    get: operations['list_audit_api_v1_audit_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/device': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Device Info
     * @description Operator picker for a registered shop-floor device.
     */
    get: operations['device_info_api_v1_auth_device_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations['login_api_v1_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout_api_v1_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/pin-login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Pin Login */
    post: operations['pin_login_api_v1_auth_pin_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations['refresh_api_v1_auth_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/devices': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register Device */
    post: operations['register_device_api_v1_devices_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/devices/{device_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke Device */
    delete: operations['revoke_device_api_v1_devices__device_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations['me_api_v1_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change Password */
    post: operations['change_password_api_v1_me_password_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me/pin': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change Pin */
    post: operations['change_pin_api_v1_me_pin_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** My Sessions */
    get: operations['my_sessions_api_v1_me_sessions_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me/sessions/{family_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke Session */
    delete: operations['revoke_session_api_v1_me_sessions__family_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me/totp/disable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Totp Disable */
    post: operations['totp_disable_api_v1_me_totp_disable_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me/totp/enable': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Totp Enable */
    post: operations['totp_enable_api_v1_me_totp_enable_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me/totp/setup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Totp Setup */
    post: operations['totp_setup_api_v1_me_totp_setup_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/org/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Org Settings */
    get: operations['get_org_settings_api_v1_org_settings_get'];
    /** Put Org Settings */
    put: operations['put_org_settings_api_v1_org_settings_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Sites */
    get: operations['list_sites_api_v1_sites_get'];
    put?: never;
    /** Create Site */
    post: operations['create_site_api_v1_sites_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sites/{site_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Site */
    get: operations['get_site_api_v1_sites__site_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Site */
    patch: operations['patch_site_api_v1_sites__site_id__patch'];
    trace?: never;
  };
  '/api/v1/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Users */
    get: operations['list_users_api_v1_users_get'];
    put?: never;
    /** Create User */
    post: operations['create_user_api_v1_users_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User */
    get: operations['get_user_api_v1_users__user_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch User */
    patch: operations['patch_user_api_v1_users__user_id__patch'];
    trace?: never;
  };
  '/api/v1/users/{user_id}/logout-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout User Everywhere */
    post: operations['logout_user_everywhere_api_v1_users__user_id__logout_all_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Healthz */
    get: operations['healthz_healthz_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/metrics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Metrics */
    get: operations['metrics_metrics_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/readyz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readyz */
    get: operations['readyz_readyz_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AlertThresholds */
    AlertThresholds: {
      /**
       * Long Stop Manager Min
       * @default 60
       */
      long_stop_manager_min: number;
      /**
       * Long Stop Supervisor Min
       * @default 15
       */
      long_stop_supervisor_min: number;
      /**
       * Oee Below Pct
       * @default 50
       */
      oee_below_pct: number;
      /**
       * Reject Rate Above Pct
       * @default 5
       */
      reject_rate_above_pct: number;
      /**
       * Unexplained Gap Min
       * @default 20
       */
      unexplained_gap_min: number;
    };
    /** AreaIn */
    AreaIn: {
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Site Id */
      site_id: number;
    };
    /** AreaOut */
    AreaOut: {
      /** Archived At */
      archived_at: string | null;
      /** Code */
      code: string;
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Site Id */
      site_id: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** AreaPatch */
    AreaPatch: {
      /** Archived */
      archived?: boolean | null;
      /** Code */
      code?: string | null;
      /** Name */
      name?: string | null;
    };
    /** AuditOut */
    AuditOut: {
      /** Action */
      action: string;
      /** Actor User Id */
      actor_user_id: number | null;
      /** After */
      after: {
        [key: string]: unknown;
      } | null;
      /** Before */
      before: {
        [key: string]: unknown;
      } | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Entity Id */
      entity_id: string | null;
      /** Entity Type */
      entity_type: string;
      /** Id */
      id: number;
      /** Ip */
      ip: string | null;
      /** Note */
      note: string | null;
      /** Request Id */
      request_id: string | null;
    };
    /** DeviceInfoOut */
    DeviceInfoOut: {
      /** Area Id */
      area_id: number | null;
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Operators */
      operators: components['schemas']['DeviceOperatorOut'][];
      /** Organization Name */
      organization_name: string;
      /** Site Id */
      site_id: number;
      /** Site Name */
      site_name: string;
    };
    /** DeviceOperatorOut */
    DeviceOperatorOut: {
      /** Employee Code */
      employee_code: string | null;
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Pin Length */
      pin_length: number | null;
    };
    /** DeviceRegisterIn */
    DeviceRegisterIn: {
      /** Area Id */
      area_id?: number | null;
      /** Name */
      name: string;
      /** Site Id */
      site_id: number;
    };
    /** DeviceRegisterOut */
    DeviceRegisterOut: {
      /** Area Id */
      area_id: number | null;
      /** Device Token */
      device_token: string;
      /** Id */
      id: number;
      /** Site Id */
      site_id: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** LoginIn */
    LoginIn: {
      /** Email */
      email: string;
      /** Password */
      password: string;
      /** Totp Code */
      totp_code?: string | null;
    };
    /** MeOut */
    MeOut: {
      /** Email */
      email: string | null;
      /** Employee Code */
      employee_code: string | null;
      /** Id */
      id: number;
      /** Language */
      language: string | null;
      /** Name */
      name: string;
      /** Organization Id */
      organization_id: number;
      /** Organization Name */
      organization_name: string;
      /** Roles */
      roles: string[];
      /** Site Ids */
      site_ids: number[];
      /** Totp Enabled */
      totp_enabled: boolean;
    };
    /** Ok */
    Ok: {
      /**
       * Ok
       * @default true
       */
      ok: boolean;
    };
    /**
     * OrgSettings
     * @description Per-organization configuration. Stored as JSON on organizations.settings; defaults fill gaps.
     */
    OrgSettings: {
      /**
       * Alert Channels
       * @default [
       *       "in_app"
       *     ]
       */
      alert_channels: ('in_app' | 'email' | 'push' | 'whatsapp' | 'sms')[];
      /**
       * @default {
       *       "long_stop_manager_min": 60,
       *       "long_stop_supervisor_min": 15,
       *       "oee_below_pct": 50,
       *       "reject_rate_above_pct": 5,
       *       "unexplained_gap_min": 20
       *     }
       */
      alert_thresholds: components['schemas']['AlertThresholds'];
      /**
       * Allow Negative Stock
       * @default false
       */
      allow_negative_stock: boolean;
      /**
       * Backflush On Output
       * @default false
       */
      backflush_on_output: boolean;
      /**
       * Currency
       * @default INR
       */
      currency: string;
      /**
       * Data Retention Days
       * @default 1095
       */
      data_retention_days: number;
      /**
       * Default Language
       * @default en
       */
      default_language: string;
      /**
       * Digest Time
       * @default 07:00
       */
      digest_time: string;
      /**
       * Low Stock Default Days
       * @default 7
       */
      low_stock_default_days: number;
      /**
       * Oee Ideal Rate Mode
       * @default product
       * @enum {string}
       */
      oee_ideal_rate_mode: 'machine' | 'product';
      /**
       * Operator Idle Lock Min
       * @default 10
       */
      operator_idle_lock_min: number;
      /**
       * Planned Changeovers
       * @default false
       */
      planned_changeovers: boolean;
      /**
       * Require 2Fa For Admins
       * @default false
       */
      require_2fa_for_admins: boolean;
      /**
       * Show Operator Analytics
       * @default false
       */
      show_operator_analytics: boolean;
      /**
       * Timezone
       * @default Asia/Kolkata
       */
      timezone: string;
      /**
       * Unit System
       * @default metric
       * @enum {string}
       */
      unit_system: 'metric' | 'imperial';
      /**
       * Week Start Day
       * @default 0
       */
      week_start_day: number;
      /**
       * Weekly Summary Day
       * @default 0
       */
      weekly_summary_day: number;
      /**
       * Working Days
       * @default [
       *       0,
       *       1,
       *       2,
       *       3,
       *       4,
       *       5
       *     ]
       */
      working_days: number[];
    };
    /** Page[AuditOut] */
    Page_AuditOut_: {
      /** Items */
      items: components['schemas']['AuditOut'][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
    };
    /** Page[UserOut] */
    Page_UserOut_: {
      /** Items */
      items: components['schemas']['UserOut'][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
    };
    /** PasswordChangeIn */
    PasswordChangeIn: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /** PinChangeIn */
    PinChangeIn: {
      /** Pin */
      pin: string;
    };
    /** PinLoginIn */
    PinLoginIn: {
      /** Pin */
      pin: string;
      /** User Id */
      user_id: number;
    };
    /**
     * Role
     * @enum {string}
     */
    Role: 'operator' | 'supervisor' | 'technician' | 'inspector' | 'storekeeper' | 'manager' | 'admin';
    /** SessionOut */
    SessionOut: {
      /** Auth Method */
      auth_method: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Current */
      current: boolean;
      /** Id */
      id: string;
      /** Ip */
      ip: string | null;
      /** Last Used At */
      last_used_at: string | null;
      /** User Agent */
      user_agent: string | null;
    };
    /** SiteIn */
    SiteIn: {
      /** Address */
      address?: string | null;
      /** Code */
      code: string;
      /** Name */
      name: string;
      /**
       * Timezone
       * @default Asia/Kolkata
       */
      timezone: string;
    };
    /** SiteOut */
    SiteOut: {
      /** Address */
      address: string | null;
      /** Archived At */
      archived_at: string | null;
      /** Code */
      code: string;
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Timezone */
      timezone: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** SitePatch */
    SitePatch: {
      /** Address */
      address?: string | null;
      /** Archived */
      archived?: boolean | null;
      /** Code */
      code?: string | null;
      /** Name */
      name?: string | null;
      /** Timezone */
      timezone?: string | null;
    };
    /** TokenOut */
    TokenOut: {
      /** Access Token */
      access_token: string;
      /** Expires In */
      expires_in: number;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      user: components['schemas']['MeOut'];
    };
    /** TotpCodeIn */
    TotpCodeIn: {
      /** Code */
      code: string;
    };
    /** TotpSetupOut */
    TotpSetupOut: {
      /** Otpauth Uri */
      otpauth_uri: string;
      /** Secret */
      secret: string;
    };
    /** UserIn */
    UserIn: {
      /** Email */
      email?: string | null;
      /** Employee Code */
      employee_code?: string | null;
      /** Language */
      language?: string | null;
      /** Name */
      name: string;
      /** Password */
      password?: string | null;
      /** Phone */
      phone?: string | null;
      /** Pin */
      pin?: string | null;
      /** Roles */
      roles: components['schemas']['Role'][];
      /**
       * Site Ids
       * @default []
       */
      site_ids: number[];
    };
    /** UserOut */
    UserOut: {
      /** Email */
      email: string | null;
      /** Employee Code */
      employee_code: string | null;
      /** Has Password */
      has_password: boolean;
      /** Has Pin */
      has_pin: boolean;
      /** Id */
      id: number;
      /** Is Active */
      is_active: boolean;
      /** Language */
      language: string | null;
      /** Last Login At */
      last_login_at: string | null;
      /** Name */
      name: string;
      /** Phone */
      phone: string | null;
      /** Roles */
      roles: string[];
      /** Site Ids */
      site_ids: number[];
      /** Totp Enabled */
      totp_enabled: boolean;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** UserPatch */
    UserPatch: {
      /** Email */
      email?: string | null;
      /** Employee Code */
      employee_code?: string | null;
      /** Is Active */
      is_active?: boolean | null;
      /** Language */
      language?: string | null;
      /** Name */
      name?: string | null;
      /** Password */
      password?: string | null;
      /** Phone */
      phone?: string | null;
      /** Pin */
      pin?: string | null;
      /** Roles */
      roles?: components['schemas']['Role'][] | null;
      /** Site Ids */
      site_ids?: number[] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_areas_api_v1_areas_get: {
    parameters: {
      query?: {
        site_id?: number | null;
        include_archived?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AreaOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_area_api_v1_areas_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AreaIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AreaOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  patch_area_api_v1_areas__area_id__patch: {
    parameters: {
      query?: never;
      header?: {
        'if-match'?: string | null;
      };
      path: {
        area_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AreaPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AreaOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_audit_api_v1_audit_get: {
    parameters: {
      query?: {
        entity_type?: string | null;
        entity_id?: string | null;
        actor_user_id?: number | null;
        action?: string | null;
        since?: string | null;
        until?: string | null;
        page?: number;
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_AuditOut_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  device_info_api_v1_auth_device_get: {
    parameters: {
      query?: never;
      header?: {
        'x-device-token'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeviceInfoOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: {
        'user-agent'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: {
        'x-csrf-token'?: string | null;
      };
      path?: never;
      cookie?: {
        fp_refresh?: string | null;
        fp_csrf?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  pin_login_api_v1_auth_pin_login_post: {
    parameters: {
      query?: never;
      header?: {
        'x-device-token'?: string | null;
        'user-agent'?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PinLoginIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: {
        'x-csrf-token'?: string | null;
        'user-agent'?: string | null;
      };
      path?: never;
      cookie?: {
        fp_refresh?: string | null;
        fp_csrf?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  register_device_api_v1_devices_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeviceRegisterIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeviceRegisterOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  revoke_device_api_v1_devices__device_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        device_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  me_api_v1_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MeOut'];
        };
      };
    };
  };
  change_password_api_v1_me_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordChangeIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  change_pin_api_v1_me_pin_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PinChangeIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  my_sessions_api_v1_me_sessions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionOut'][];
        };
      };
    };
  };
  revoke_session_api_v1_me_sessions__family_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        family_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  totp_disable_api_v1_me_totp_disable_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TotpCodeIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  totp_enable_api_v1_me_totp_enable_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TotpCodeIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Ok'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  totp_setup_api_v1_me_totp_setup_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TotpSetupOut'];
        };
      };
    };
  };
  get_org_settings_api_v1_org_settings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrgSettings'];
        };
      };
    };
  };
  put_org_settings_api_v1_org_settings_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OrgSettings'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrgSettings'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_sites_api_v1_sites_get: {
    parameters: {
      query?: {
        include_archived?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SiteOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_site_api_v1_sites_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SiteIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SiteOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_site_api_v1_sites__site_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        site_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SiteOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  patch_site_api_v1_sites__site_id__patch: {
    parameters: {
      query?: never;
      header?: {
        'if-match'?: string | null;
      };
      path: {
        site_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SitePatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SiteOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_users_api_v1_users_get: {
    parameters: {
      query?: {
        q?: string | null;
        role?: components['schemas']['Role'] | null;
        active?: boolean | null;
        page?: number;
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_UserOut_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_user_api_v1_users_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserIn'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_user_api_v1_users__user_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  patch_user_api_v1_users__user_id__patch: {
    parameters: {
      query?: never;
      header?: {
        'if-match'?: string | null;
      };
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserPatch'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_user_everywhere_api_v1_users__user_id__logout_all_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  metrics_metrics_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  readyz_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
}
